create table noteful_notes(
    note_id integer primary key generated by default as identity,
    note_name text not null,
    modified timestamptz default now(),
    folder_id integer references noteful_folders(folder_id) on delete cascade not null,
    content text not null
);